/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "878cd31214ac27a3996927cd5c9c138b10c9fc8d"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
